# Generated by Django 4.2.13 on 2024-06-19 05:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'NearbyPlaces',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='properties/')),
                ('no_of_bedrooms', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of Bedrooms Must be positive')])),
                ('no_of_bathrooms', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of Bathrooms Must be positive')])),
                ('no_of_floor', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0, 'No of Floor Must be positive')])),
                ('no_of_likes', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of likes Must be positive')])),
                ('url', models.URLField(blank=True, null=True)),
                ('nearby', models.ManyToManyField(to='seller.nearbyplaces')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.property')),
            ],
            options={
                'unique_together': {('property', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.property')),
            ],
            options={
                'verbose_name_plural': 'Interested',
                'unique_together': {('property', 'profile')},
            },
        ),
    ]
