# Generated by Django 4.2.13 on 2024-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_property_no_of_floor_alter_property_no_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='1', upload_to='properties/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nearbyplaces',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
