# Generated by Django 4.2.13 on 2024-05-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_name'),
        ('seller', '0003_property_image_alter_nearbyplaces_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.property')),
            ],
            options={
                'unique_together': {('property', 'profile')},
            },
        ),
    ]
