# Generated by Django 4.2.13 on 2024-05-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_number'),
        ('seller', '0004_property_no_of_likes_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.property')),
            ],
            options={
                'unique_together': {('property', 'profile')},
            },
        ),
    ]
