# Generated by Django 4.2.13 on 2024-05-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_interested_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nearbyplaces',
            options={'verbose_name_plural': 'NearbyPlaces'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
