# Generated by Django 4.2.13 on 2024-06-07 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_nearbyplaces_options_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bathrooms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of Bathrooms Must be positive')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bedrooms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of Bedrooms Must be positive')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_floor',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0, 'No of Floor Must be positive')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_likes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'No of likes Must be positive')]),
        ),
    ]
