# Generated by Django 4.2.13 on 2024-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
